### ISSUE TITLE
Add method for Rect and RectF

### ISSUE THREAD

**Issue by jordan1997** [schoolhelper/androidgraphextension#25]
Implement the following methods for the Rect and RectF:

1. Rect.contains(Point)
2. Rect.contains(PointF)
3. Rect.contains(Rect) - true if rectangle contain another rectangle
4. Add all method from Rect to RectF too.

Add documentation and tests if possible, if not create an issue to implement test and write documentation for the added methods.

**Comment by yoavst** [comment]
I'll do it.
